### ISSUE TITLE
Changes in the 2nd Edition?

### ISSUE THREAD

**Issue by rajaseelan** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#1]
Hi @stefmolin , really silly question - what are the changes in the 2nd ed?  
I can't seem to Google that.

**Comment by stefmolin** [comment]
All the code examples have been updated for newer versions of the libraries used, and there are new/revised examples highlighting new features. For pandas in particular, the first edition uses a much older version than what is currently available (pre 1.0), and this version uses the latest (1.x). You can look through the pandas documentation for the [release notes](https://pandas.pydata.org/docs/whatsnew/index.html) to see all the changes that have happened since the version of pandas used in the first edition (0.23.4). In addition, there are significant changes to the content of some chapters, while others have new examples and/or datasets.

Hope that helps.

**Comment by rajaseelan** [comment]
Thank you for that extremely quick reply.
Colleagues loved the 1st ed. 
Looks like it's time for a purchase.

**Comment by davidgallagher-max** [comment]
Hi Stef Molin - When installing the requirements in the virtual environment as per page 39, I ran into an error under Scipy "Preparing wheel metadata":

ERROR: Could not find a version that satisfies the requirement scipy==1.5.2 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0b1, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.1.0rc1, 1.1.0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0rc1, 1.4.0rc2, 1.4.0, 1.4.1, 1.5.0rc1, 1.5.0rc2, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0rc1, 1.6.0rc2, 1.6.0, 1.6.1, 1.6.2, 1.6.3)
ERROR: No matching distribution found for scipy==1.5.2

I'm on a MacBook Pro Big Sur, using a conda virtual environment.
