### ISSUE TITLE
Problems trying to install visual-aids

### ISSUE THREAD

**Issue by tpp1360** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#13]
Dear Stefmolin, I tried to install this package but I couldn't. Windows 11, Python 3.8.8.

**Comment by stefmolin** [comment]
@tpp1360 - Without detailed information of the commands you ran and their outputs, I can only guess what could be the issue. Can you confirm that you **completely** followed the environment setup directions in the book starting on page 34?

---

Note that missing or skipping a step in the directions could be the issue. Double-check these steps:
1. **Clone your fork**: I can see that you have forked the repository, so once you clone your fork, you will have all the files needed to install the `visual-aids` package on your machine. If you don't clone your fork, you won't be able to install it.
2. **Change directories**: If you have already cloned your fork, you need to change directories to the cloned repository so that `pip` can find them.

**Comment by stefmolin** [comment]
Closing this issue since I haven't heard from you.
