### ISSUE TITLE
M1 Mac Problem: nothing provides requested libgfortran 5.0.0.dev0**

### ISSUE THREAD

**Issue by Afinque** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#38]
### Required attestation
- [ x] I have **completely and exactly** followed the virtual environment setup instructions from the book and have consulted the [README](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#notes-on-environment-setup) for any updates.
Comment: I followed the README instructions for M1 Macs.

- [ x] I have cloned either this repository or my fork of this repository so that I have all necessary files on my local machine.
- [x ] I have checked that this issue has not already been reported or resolved [here](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/issues?q=is%3Aissue+label%3Atroubleshooting).
- [x ] I am aware that there is a [pre-built Binder environment](https://mybinder.org/v2/gh/stefmolin/binder-environments/2nd_edition?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fstefmolin%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%26urlpath%3Dlab%252Ftree%252FHands-On-Data-Analysis-with-Pandas-2nd-edition%252F%26branch%3Dmaster) that I can use, but I want to install locally on my machine instead.

---

##### 1. Which OS are you using?
MacOS 12.6.3 M1 chip

##### 2. Which Python version are you using?
3.9.7

##### 3. Are you using `conda` or `venv`?
mamba

---

### Commands run and their outputs
The commands (or concepts) that I ran were:

forked the repo
cloned repo using github desktop
cd into repo directory on local

Then,
conda install mamba -n base -c conda-forge
mamba env create --file m1_environment.yml

### Screenshots

Output of the above commands yields:

<img width="1095" alt="Screen Shot 2023-02-27 at 6 34 06 AM" src="https://user-images.githubusercontent.com/10910341/221577291-0d07eabe-12cc-4186-9de2-380e60ba700e.png">

**Comment by stefmolin** [comment]
From your screenshot, mamba is not looking for ARM-compatible packages, but rather for ones that would work with the old chip architecture (Intel chip). See where it says `conda-forge/osx-64` in your screenshot? For Apple Silicon chips, this would be `conda-forge/osx-arm64`. It seems that you have an Intel chip rather than an M1 chip, in which case you would follow the instructions as laid out in the book (i.e., use the `environment.yml` file and not the `m1_environment.yml` file).

This package is still available on [conda-forge](https://anaconda.org/conda-forge/libgfortran/files?version=5.0.0.dev0), but only for osx-arm64 architectures (Apple Silicon chips). This package is only needed for Apple Silicon chips, and it is only available for ARM chips (not Intel). If you do have an Apple Silicon chip, then I'm not sure what is going wrong since I'm not able to reproduce this on my machine.

**Comment by Afinque** [comment]
Thanks for your quick response! I definitely have an Apple M1, so I will investigate and post any results I find here.
