### ISSUE TITLE
Problem Downloading the Solutions!

### ISSUE THREAD

**Issue by nsrinivasan80** [stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition#4]
Bought the Book! But unable to download the solutions.

**Comment by stefmolin** [comment]
Hi @nsrinivasan80,

The solutions are in this repository :) Either click [here](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas-2nd-edition/tree/master/solutions) and navigate to the chapter you want or simply open the files you cloned locally when you setup your environment in chapter 1. Sometimes files are too big to display in the browser so you best bet is to use the local copy obtained in chapter 1 (they are in the `Hands-On-Data-Analysis-with-Pandas-2nd-edition/solutions/` folder).

**Comment by nsrinivasan80** [comment]
Stefanie,

Thanks for your kind response. I am very much obliged.

However, I am new to github.
I would like to work with your book. I also want to try the exercises.

When doing the exercises, especially in programming, you can always produce
an answer, but usually it is wrong!
to give you an example, I am currently trying to learn "Resampling" in
Pandas. I want to "Resample" weekly averages.
Yes, i get the answer. The result shows the first row is the average of the
first three entries in the original DataFrame,
but the rest of the rows are correctly the weekly averages. I do NOT
understand the results.

I am disabled. Also remote. There is no one to ask.

But, I digress.

I am new to github. If you can please tell me how I can download the
Solutions, I will indeed be much obliged.

Best Regards,
N. Srinivasan

**Comment by stefmolin** [comment]
I'm having a lot of trouble understanding what the issue is here. Can you tell me how you set up your environment? Did you follow the instructions in chapter 1 to get the content of this repo? I can see you forked this repo, so I'm guessing you did follow the setup directions. When you open JupyterLab from the `Hands-On-Data-Analysis-with-Pandas-2nd-edition/` folder on your local machine, what does the screen look like? It should look like figure 1.18 in the JupyterLab section of chapter 1 in the book. In the file browser pane to the left, you will see the `solutions/` folder underneath `ch_12/`. The way you navigate to the `ch_01/` folder to test the environment is the same way to navigate to the `solutions/` folder. 

When you cloned your forked repo, you got all the files in the repository on your local machine, including the solutions -- there is no need to download them again. If you followed the directions in chapter 1, then you already have the solutions on your computer, and it's just a matter of opening the files in JupyterLab on your computer. Just navigate to the `solutions/` folder and then find the chapter you want to check -- the solutions are always in notebooks for you to run:
![image](https://user-images.githubusercontent.com/24376333/118359512-c9f22480-b551-11eb-870f-947df3a4d752.png)
 
You said chapter 4, so click `ch_04` next:
![image](https://user-images.githubusercontent.com/24376333/118359568-10478380-b552-11eb-9942-fe331a54ab9e.png)

Then open the notebook:
![image](https://user-images.githubusercontent.com/24376333/118359594-3a994100-b552-11eb-9fc5-6607b2214aac.png)


If you always start JupyterLab from the `Hands-On-Data-Analysis-with-Pandas-2nd-edition/` folder and then select the chapter, you will always be able to navigate to the solutions from there. If you open JupyterLab from a folder for a specific chapter, you will not since it only shows files in the current folder and all subfolders. For example, if you launch JupyterLab from the `ch_04/` folder, notice the file browser doesn't have the other chapters or the solutions:

![image](https://user-images.githubusercontent.com/24376333/118359668-8c41cb80-b552-11eb-8f1d-24ccdec63115.png)

**Comment by nsrinivasan80** [comment]
Thank you, I got it.
